buckets:
  price: [0, 25, 50, 100, 200, 500, 1000]
  average_rating: [0.0, 3.5, 4.0, 4.5, 5.0]
  rating_number: [0, 10, 100, 1000, 10000]
bsi:
  price:
    scale: 100
    bits: 20
  average_rating:
    scale: 100
    bits: 10
  rating_number:
    scale: 1
    bits: 20
